# Generated by Django 5.1.3 on 2024-11-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название комнаты')),
                ('detail', models.TextField(max_length=500, verbose_name='Описание')),
                ('room_type', models.CharField(choices=[('single', 'Одноместный'), ('double', 'Двухместный'), ('suite', 'Люкс')], max_length=20, verbose_name='Тип комнаты')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за ночь')),
                ('available', models.BooleanField(default=True, verbose_name='Доступна для бронирования')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_images/', verbose_name='Фото комнаты')),
            ],
        ),
    ]
